### ISSUE TITLE
Can't seem to get all the downloading sorted out

### ISSUE THREAD

**Issue by GillianZech** [comp426-2022-spring/a00#11]
We downloaded similar programs for comp211 and other comp classes, so I'm having trouble figuring out which stuff I already have and which stuff I still need. For the things I know I need, I can't seem to download them because I keep getting told "command not found" when I use "sudo." Would like to meet in office hours tonight after 6:30 or almost anytime tomorrow.

**Comment by jdmar3** [comment]
We can definitely sort this out.

What OS are you on? 

What things do you know for sure are missing?

**Comment by GillianZech** [comment]
I'm on Windows. I believe I have WSL because we needed it for 211; the way I always accessed it then was through Windows Powershell and opening a container with Docker Desktop specifically for that class. I don't know how to access it other than that; should I redownload it a different way so it is more accessible? Other than that, I'm pretty sure I have everything except all the node.js-related stuff (nvm, node.js, npm).

**Comment by jdmar3** [comment]
I assigned Cameron because he will probably be better able to help with Windows related issues in more specific detail. I can only give broad strokes.

I can't know what you already have installed or how you got to it before for different classes. If you already have a way that works for you, then do that, but if you are not sure if something is installed or not, then that is where we have to start. Do you have WSL installed or not? If the answer is not an unequivocal yes, then follow the instructions for getting started with using it in VSCode here: https://code.visualstudio.com/docs/remote/wsl#_getting-started

I've also linked these things on this page from the assignment instructions so you have all of the links in one handy spot: https://comp426.johndmart.in/guide/software/windows/

Go through the getting started guide and let us know if that works. Once you have done that, then install Node using nvm if you can because it installs everything for you. Node is also really the important thing to have here. That is what we are actually using. It just lives inside these other layers of OSes and dependencies.

**Comment by GillianZech** [comment]
Update: I was able to complete a00 and pass the autograder, so I seem to be fine with what I have. We'll just have see later on if I run into any more problems. Thanks!

**Comment by jdmar3** [comment]
Yay! Awesome!
