### ISSUE TITLE
npm init issue... but I downloaded js software?

### ISSUE THREAD

**Issue by Josh-Dillon-1223** [comp426-2022-spring/a00#13]
Hello, I'm using Ubuntu and I tried using the 'npm init' command, and followed all downloads to the T. However, when my node software was downloading, I was having issues running npm init, as it threw this error:

 /usr/bin/env: ‘bash\r’: No such file or directory

Does anyone know what is going on? It says that this has something to do with Windows syntax? I'm unsure fully of what this problem is, and I'm having trouble locating this in my software.

**Comment by jdmar3** [comment]
Can you post a screenshot?

Also, if you do /which/npm, what happens?

If you installed Node with NVM, then npm should be installed in ~/.nvm/versions/node/v16.13.2/bin/npm.

If you installed Node using apt, then you will likely have to install npm as well. This is because you can also install npm and Yarn and other Node things from the Ubuntu repositories because they have made them system packages.

I would recommend uninstalling Node at system level and using NVM instead, because it will make sure that you are on the current LTS version (v16.13.2) which is newer than the version available in Ubuntu (probably) and is the one that we are using for class.

**Comment by Josh-Dillon-1223** [comment]
Sorry, I worked a bit and figured out what was going on. I think I have two copies of nodejs on my computer - one in Ubuntu and now one on my system. I'll just be using Ubuntu from here on. Thanks
