### ISSUE TITLE
Can't push and can't generate a ssh key

### ISSUE THREAD

**Issue by bcoop2000** [comp426-2022-spring/a00#15]
<img width="960" alt="a00 issue" src="https://user-images.githubusercontent.com/69535172/150702843-9b9b3b88-77a5-41ad-9633-0efe75ef9225.png">

I tried to generate an ssh and then use this command (based on the advice of some help page I found) "git remote set-url origin" to make it possible to push through the ssh. But now i still cant push and when I try to make a different ssh it gives me this message.

**Comment by camsimba** [comment]
Hey, let me see if I can help a bit. It looks like when you use `git push` here, you are pushing to a repository labeled `tmp.git` under your account, not to your assignment repository (`https://github.com/comp426-2022-spring/a00-bcoop2000.git`). This might be due to you using the command that you listed above, `git remote set-url origin`. It isn't that `git push` isn't working for you, it's that the repository you are trying to target doesn't exist. 

Could you run the following command and tell me what it says or screenshot it for me -> `git remote -v`. This should list what your fetch and push urls are set to, and I just want to verify that you have the correct addresses.

**Comment by bcoop2000** [comment]
that returns
origin  https://github.com/bcoop2000/tmp.git/ (fetch)
origin  https://github.com/bcoop2000/tmp.git/ (push)

**Comment by camsimba** [comment]
Okay cool, this should be a quick fix. What I believe happened here is whatever tutorial you used wanted you to try out using the ssh key, so they gave you an example command to run to target a new repository. However, you used this while in the repository for a00, so it messed things up. Basically, you changed the target (origin) of your local copy of the repository away from 'https://github.com/comp426-2022-spring/a00-bcoop2000.git' to the example repository 'https://github.com/bcoop2000/tmp.git', so any changes you do on your local machine will be pushed to the example repository instead.

If I am right, this should fix it. Try executing this command -> `git remote set-url origin https://github.com/comp426-2022-spring/a00-bcoop2000.git`. This should change origin back to the a00 repository. Afterwards, type `git remote -v`. It should now list 'https://github.com/comp426-2022-spring/a00-bcoop2000.git' as your fetch and push repository. If so, you should be able to `git push` now. 

Let me know if this didn't work and we can work on it some more, and if you could post a screenshot of it if it fails it would be useful!

**Comment by bcoop2000** [comment]
That worked. Thank you!

**Comment by camsimba** [comment]
Awesome, I'll go ahead and close the issue!
