### ISSUE TITLE
So my token is actually invalid 

### ISSUE THREAD

**Issue by sadye** [comp426-2022-spring/a00#5]
<img width="525" alt="Screen Shot 2022-01-14 at 10 10 57 AM" src="https://user-images.githubusercontent.com/77740595/149538466-dc368615-4ab5-428b-889b-7217b76aa9bc.png">
I got this email yesterday and became unable to push my work.
Whenever I try to push it I get an error saying

remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/comp426-2022-spring/a00-sadye.git/'

I have tried logging in and out and making a new access token and trying to sign in using that as a password. Any help would be great.

**Comment by camsimba** [comment]
Hi, let me see if I can help some. The error you got occurs when you commit a personal access token in plaintext to a public repository. Basically, the token you use to access git and confirm yourself was posted in a file you pushed where others could see. Git recognized this within your code, and automatically revoked the token so that nobody could use it without your permission. Looking through your repository, it seems that you included it within index.html on line 47, 99, 115, and 134. I'm not sure how they ended up there, but Git recognized these as your PAT (Personal Access Token) and automatically disabled it. Without it, you will not be able to push anything to your git account. You will need to create a new Git Personal Access Token and add it locally to your computer. Information on how to do this can be found in the git documentation here: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
Hope this helped! If you need more help, just shoot another comment at me in this thread and I will see it!

**Comment by sadye** [comment]
<img width="553" alt="Screen Shot 2022-01-14 at 5 44 50 PM" src="https://user-images.githubusercontent.com/77740595/149595188-45c6ff7b-2681-4704-b36a-a240053ac84c.png">
I followed these directions and got this error

**Comment by camsimba** [comment]
So, what you entered was actually the example of what you might do with a repo. Within the link https://github.com/username/repo.git , 'username' and 'repo.git' are just placeholders for an actual username and repository. Thus, it would error out since 'username' and 'repo.git' aren't usernames nor repositories. Ignore this example, as it isn't helpful for us. What we want is for the computer to ask for your credentials again, which it looks like it has when you executed that command, so that it can cache it on your computer. Try pushing your code like before, but without the old PATs in index.html and let me know what happens.

**Comment by sadye** [comment]
I get the same error about authentication that does not allow me to sign into the github from the terminal

**Comment by camsimba** [comment]
Hm, I would make sure you aren't pushing your newly generated PAT in any of your code and then try looking up a tutorial for creating and adding a new Personal Access Token. What I think is happening is that the new PAT that you generated isn't linked yet to your local machine, and so it is rejecting any modifications. I'm not super well versed on this subject, so I think a youtube video would probably help more than I could, but if this is still causing you issues after trying to work with it tomorrow (Monday) then I'm willing to dig a little deeper with you to solve this issue. Just keep me posted tomorrow and I'll be here to help!

**Comment by camsimba** [comment]
Just checking back in with this, let me know if you still need any help!

**Comment by sadye** [comment]
YES it got figure out-- sorry about the delayed response

**Comment by camsimba** [comment]
Awesome, glad you figured it out! I'll go ahead and close this issue.
